const data = {
    products: [
    {
        _id: '1',
        name: 'Nike Slim Shrrt',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Nike',
        rating: 3.0,
        numReviews: 10,
        description: 'high quality product',
    },
    {
        _id: '2',
        name: 'Adidas Slim Shrrt',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Adidas',
        rating: 4.1,
        numReviews: 9,
        description: 'high quality product',
    },
    {
        _id: '3',
        name: 'Sogol Slim Shrrt',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Sogol',
        rating: 4.9,
        numReviews: 10,
        description: 'high quality product',
    },
    {
        _id: '4',
        name: 'Lacoste Slim Shrrt',
        image: '/images/p1.jpg',
        price: 110,
        brand: 'Lacoste',
        rating: 3.5,
        numReviews: 10,
        description: 'high quality product',
    },
    {
        _id: '5',
        name: 'Bucoste Slim Shrrt',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Bucoste',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
    },
    {
        _id: '6',
        name: 'Bratang Slim Shrrt',
        image: '/images/p1.jpg',
        price: 120,
        brand: 'Bratang',
        rating: 4.2,
        numReviews: 10,
        description: 'high quality product',
    },
    ],
};

export default data;